# Generated by Django 3.1.4 on 2020-12-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('Foto', models.ImageField(blank=True, upload_to='Mascota', verbose_name='Foto de perfil')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Tipo Blog',
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Apellidos', models.CharField(max_length=150, verbose_name='Nombres')),
                ('DNI', models.CharField(max_length=8, verbose_name='DNI')),
                ('Telefono_Celular', models.CharField(max_length=10, verbose_name='Teléfono celular')),
                ('Foto', models.ImageField(blank=True, upload_to='Cliente', verbose_name='Foto de perfil')),
                ('Direccion', models.TextField(verbose_name='Dirección')),
                ('Correo_User', models.EmailField(max_length=200, verbose_name='Correo usuario')),
                ('Contrasenia', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliete',
                'verbose_name_plural': 'Clientes',
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Especie', models.CharField(max_length=100, verbose_name='Especie')),
                ('Raza', models.CharField(max_length=100, verbose_name='Raza')),
                ('Edad', models.IntegerField(default=0, verbose_name='Edad en meses')),
                ('Color', models.CharField(max_length=100, verbose_name='Color')),
                ('Peso', models.IntegerField(default=0, verbose_name='Peso en Gramo')),
                ('Temperatura_C', models.IntegerField(default=0, verbose_name='Temperatura Corporal')),
                ('Observaciones', models.CharField(max_length=300, verbose_name='Observaciones')),
                ('Fecha_Nacimiento', models.DateField(verbose_name='Fecha nacimiento')),
                ('Foto', models.ImageField(blank=True, upload_to='Mascota', verbose_name='Foto de perfil')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.cliente')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('Foto', models.ImageField(blank=True, upload_to='Mascota', verbose_name='Foto de perfil')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('Cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo Vacuna',
                'verbose_name_plural': 'Tipo Vacunas',
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMVP', models.CharField(max_length=10, verbose_name='CMPV')),
                ('Nombre_Apellidos', models.CharField(max_length=150, verbose_name='Nombres')),
                ('DNI', models.CharField(max_length=8, verbose_name='DNI')),
                ('Telefono_Celular', models.CharField(max_length=10, verbose_name='Teléfono celular')),
                ('Direccion', models.TextField(verbose_name='Dirección')),
                ('CorreoUser', models.EmailField(max_length=200, verbose_name='Correo usuario')),
                ('Contrasenia', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('Foto', models.ImageField(blank=True, upload_to='Veterinario', verbose_name='Foto de perfil')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veterinario',
                'verbose_name_plural': 'Veterinarios',
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta_Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Programada', models.DateField(verbose_name='Fecha Programada')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('Fecha_Aplicada', models.DateField(blank=True, verbose_name='Fecha Aplicada')),
                ('Costo', models.IntegerField(default=0, verbose_name='Costo en soles S/')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
                ('Mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
                ('Tipo_Vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.tipo_vacuna')),
                ('Veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.veterinario')),
            ],
            options={
                'verbose_name': 'Tarjeta vacuna',
                'verbose_name_plural': 'Tarjeta vacunas',
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='ServicioCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Internado', models.DateField(verbose_name='Fecha internado')),
                ('Sintomas', models.TextField(verbose_name='Sintomas')),
                ('Diagnostico', models.TextField(verbose_name='Diagnostico')),
                ('Tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('Mejora_Descripcion', models.TextField(verbose_name='Mejora en los días internado')),
                ('Costo', models.IntegerField(default=0, verbose_name='Costo en soles S/')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
                ('Mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
                ('Veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.veterinario')),
            ],
            options={
                'verbose_name': 'Servicio IC',
                'verbose_name_plural': "Servico IC's",
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='Servicio_Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(verbose_name='Fecha del servicio')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('Costo', models.IntegerField(default=0, verbose_name='Costo en soles S/')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
                ('Mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
                ('Veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.veterinario')),
            ],
            options={
                'verbose_name': 'Servicio simple',
                'verbose_name_plural': 'Servicios simples',
                'ordering': ['Creado'],
            },
        ),
        migrations.CreateModel(
            name='Servicio_Completo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sintomas', models.TextField(verbose_name='Sintomas')),
                ('Diagnostico', models.TextField(verbose_name='Diagnostico')),
                ('Tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('Descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('Costo', models.IntegerField(default=0, verbose_name='Costo en soles S/')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
                ('Mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
                ('Veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.veterinario')),
            ],
            options={
                'verbose_name': 'Servicio completo',
                'verbose_name_plural': 'Servico completos',
                'ordering': ['Creado'],
            },
        ),
    ]
